AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  movie-therapy-backend

Globals:
  Function:
    Timeout: 3
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.13
      Timeout: 20
      MemorySize: 512
      Policies:
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
        ChatApiGet:
          Type: Api
          Properties:
            Path: /chat
            Method: get
        ChatApiPost:
          Type: Api
          Properties:
            Path: /chat
            Method: post
        ChatApiOptions:
          Type: Api
          Properties:
            Path: /chat
            Method: options

Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for the Prod stage of HelloWorldFunction
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: ARN of the HelloWorldFunction
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: IAM Role ARN created for HelloWorldFunction
    Value: !GetAtt HelloWorldFunctionRole.Arn
